export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const FETCH_TOP_RATED_MOVIES = "FETCH_TOP_RATED_MOVIES";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
export const FETCH_MOVIE_TRAILER = "FETCH_MOVIE_TRAILER";
export const FETCH_MOVIE_SEARCH = "FETCH_MOVIE_SEARCH"